using System;
using System.Collections.Generic;
using System.Diagnostics;

namespace DistinctPowers
{
    class Program
    {
        static void Main(string[] args)
        {
            int coeffLimit = 100, powerLimit = coeffLimit;
            HashSet<double> results = new HashSet<double>();

            Stopwatch timer = Stopwatch.StartNew();

            for (double c = 2; c <= coeffLimit; c++)
                for (double p = 2; p <= powerLimit; p++)
                    results.Add(Math.Pow(c, p));

            timer.Stop();
            Console.WriteLine($"There are {results.Count} distinct terms generated by a^b" +
                "\nfor all integer combinations of a and b where 2 ≤ a ≤ 100 " +
                "and 2 ≤ b ≤ 100");
            Console.WriteLine($"Problem solved in {timer.Elapsed.TotalMilliseconds:F2}ms");
        }
    }
}